Repository Passimx/notifications-service, pull requests merged in 2025-04, with the labels that each got.

#3 1 добавить key value storage
  .env.example
  docker-compose.yml
  package-lock.json
  package.json
  src/common/envs/envs.ts
  src/modules/app.module.ts
  src/modules/caching/caching.module.ts
  src/modules/caching/caching.service.ts
  src/modules/socket/raw/socket-server.ts
Labels: feature

#4 Create njsscan.yml
  .github/workflows/njsscan.yml
Labels: ci-cd

#5 ci-cd: change rules
  .github/workflows/github-actions.yml
  .github/workflows/njsscan.yml
  docker-compose.yml
Labels: ci-cd

#6 fix: bug method set
  docker-compose.yml
  src/modules/caching/caching.service.ts
Labels: bug

#13 доработал метод join
  api/swagger.json
  src/modules/socket/raw/socket-server.ts
  src/modules/socket/types/event.enum.ts
Labels: refactor

#15 refactor: correct DataResponse
  src/modules/queue/dto/data-response.dto.ts
  src/modules/socket/raw/socket-server.ts
  src/modules/socket/socket.gateway.ts
Labels: refactor

#16 refactor: correct chatOnline
  src/modules/socket/raw/socket-server.ts
  src/modules/socket/types/chat-online.type.ts
Labels: refactor

#10 добавил ping/pong
  api/swagger.json
  src/common/envs/envs.ts
  src/modules/socket/raw/socket-server.ts
  src/modules/socket/socket.gateway.ts
  src/modules/socket/types/client-socket.type.ts
  src/modules/socket/types/event.enum.ts
Labels: feature

#17 refactor: change CHAT_COUNT_ONLINE
  src/modules/socket/raw/socket-server.ts
Labels: refactor
